# coding: utf-8
from sqlalchemy import Column, DateTime, MetaData, String, Table, text


metadata = MetaData()


t_vallusers2u = Table(
    'vallusers2u', metadata,
    Column('v_Uid', String(15), nullable=False, server_default=text("' '")),
    Column('v_Locale', String(2)),
    Column('v_Sn', String(40)),
    Column('v_GivenName', String(40)),
    Column('v_MiddleName', String(40)),
    Column('v_UpperSn', String(40)),
    Column('v_UpperGivenName', String(40)),
    Column('v_UpperMiddleName', String(40)),
    Column('v_LocalSn', String(40)),
    Column('v_LocalGivenName', String(40)),
    Column('v_LocalMiddleName', String(40)),
    Column('v_JpYomiSn', String(40)),
    Column('v_JpYomiGivenName', String(40)),
    Column('v_Net23MailAddress', String(100)),
    Column('v_Mail', String(100)),
    Column('v_LocalMailAddress', String(100)),
    Column('v_Mobile', String(20)),
    Column('v_Pager', String(20)),
    Column('v_TelephoneNumber', String(20)),
    Column('v_TelephoneNumber2', String(20)),
    Column('v_TelephoneNumber3', String(20)),
    Column('v_ExtensionNumber', String(20)),
    Column('v_ExtensionNumber2', String(20)),
    Column('v_ExtensionNumber3', String(20)),
    Column('v_FacsimileTelephoneNumber', String(20)),
    Column('v_ExtensionFacsimileNumber', String(20)),
    Column('v_ContractorCode', String(10)),
    Column('v_ContractorCompany', String(100)),
    Column('v_ContractorLocalCompany', String(100)),
    Column('v_TitleLevel', String(1)),
    Column('v_EmploymentType', String(1)),
    Column('v_Description', String(120)),
    Column('v_LocalDescription', String(120)),
    Column('v_ManagerUid', String(15)),
    Column('v_L', String(3)),
    Column('v_C', String(2)),
    Column('v_CompanyCode', String(10)),
    Column('v_OldCompanyCode', String(6)),
    Column('v_Company', String(100)),
    Column('v_UpperCompany', String(10)),
    Column('v_LocalCompany', String(100)),
    Column('v_JpYomiCompany', String(160)),
    Column('v_CompanyDisc', String(4)),
    Column('v_ConnectiveType', String(1)),
    Column('v_CompanyPostalCode', String(20)),
    Column('v_CompanyPostalAddress', String(120)),
    Column('v_CompanyLocalPostalAddress', String(120)),
    Column('v_CompanyTelephoneNumber', String(20)),
    Column('v_GlobalCompanyCode', String(12)),
    Column('v_UpperGlobalCompanyCode', String(12)),
    Column('v_LocalOuCode', String(6)),
    Column('v_Ou', String(255)),
    Column('v_UpperOu', String(255)),
    Column('v_LocalOu', String(255)),
    Column('v_LocalOperationDivisionCode', String(6)),
    Column('v_OperationDivisionName', String(255)),
    Column('v_LocalOperationDivisionName', String(128)),
    Column('v_LocalDivisionCode', String(6)),
    Column('v_DivisionName', String(255)),
    Column('v_LocalDivisionName', String(128)),
    Column('v_LocalDepartmentCode', String(6)),
    Column('v_DepartmentName', String(255)),
    Column('v_LocalDepartmentName', String(128)),
    Column('v_LocalSectionCode', String(6)),
    Column('v_SectionName', String(255)),
    Column('v_LocalSectionName', String(128)),
    Column('v_TeamCode', String(4)),
    Column('v_GlobalFunctionCode', String(12)),
    Column('v_UpperGlobalFunctionCode', String(12)),
    Column('v_LocalTitleCode', String(2)),
    Column('v_Title', String(80)),
    Column('v_UpperTitle', String(80)),
    Column('v_LocalTitle', String(80)),
    Column('v_OfficeCode', String(4)),
    Column('v_OfficeName', String(100)),
    Column('v_UpperOfficeName', String(100)),
    Column('v_LocalOfficeName', String(100)),
    Column('v_OfficePostalCode', String(20)),
    Column('v_OfficePostalAddress', String(120)),
    Column('v_LocalOfficePostalAddress', String(120)),
    Column('v_OfficeTelephoneNumber', String(20)),
    Column('v_GlobalBusinessCode', String(2))
)


t_vroleuser = Table(
    'vroleuser', metadata,
    Column('v_RoleId', String(6), nullable=False, server_default=text("' '")),
    Column('v_MemberUserId', String(15)),
    Column('v_CreateDate', DateTime),
    Column('v_UpdateDate', DateTime),
    Column('v_DirectoryReflectStartDate', DateTime),
    Column('v_DirectoryReflectEndDate', DateTime)
)


t_vusers = Table(
    'vusers', metadata,
    Column('v_Uid', String(15), nullable=False, server_default=text("' '")),
    Column('v_Locale', String(2)),
    Column('v_Sn', String(40)),
    Column('v_GivenName', String(40)),
    Column('v_MiddleName', String(40)),
    Column('v_LocalSn', String(40)),
    Column('v_LocalGivenName', String(40)),
    Column('v_LocalMiddleName', String(40)),
    Column('v_JpYomiSn', String(40)),
    Column('v_JpYomiGivenName', String(40)),
    Column('v_Net23MailAddress', String(100)),
    Column('v_Mail', String(100)),
    Column('v_LocalMailAddress', String(100)),
    Column('v_Mobile', String(20)),
    Column('v_Pager', String(20)),
    Column('v_TelephoneNumber', String(20)),
    Column('v_TelephoneNumber2', String(20)),
    Column('v_TelephoneNumber3', String(20)),
    Column('v_ExtensionNumber', String(20)),
    Column('v_ExtensionNumber2', String(20)),
    Column('v_ExtensionNumber3', String(20)),
    Column('v_FacsimileTelephoneNumber', String(20)),
    Column('v_ExtensionFacsimileNumber', String(20)),
    Column('v_ContractorCode', String(10)),
    Column('v_ContractorCompany', String(100)),
    Column('v_ContractorLocalCompany', String(100)),
    Column('v_TitleLevel', String(1)),
    Column('v_EmploymentType', String(1)),
    Column('v_Description', String(120)),
    Column('v_LocalDescription', String(120)),
    Column('v_ManagerUid', String(15)),
    Column('v_L', String(3)),
    Column('v_C', String(2)),
    Column('v_CompanyCode', String(10)),
    Column('v_OldCompanyCode', String(6)),
    Column('v_Company', String(100)),
    Column('v_LocalCompany', String(100)),
    Column('v_JpYomiCompany', String(160)),
    Column('v_CompanyDisc', String(4)),
    Column('v_ConnectiveType', String(1)),
    Column('v_CompanyPostalCode', String(20)),
    Column('v_CompanyPostalAddress', String(120)),
    Column('v_CompanyLocalPostalAddress', String(120)),
    Column('v_CompanyTelephoneNumber', String(20)),
    Column('v_GlobalCompanyCode', String(32)),
    Column('v_LocalOuCode', String(6)),
    Column('v_Ou', String(255)),
    Column('v_LocalOu', String(255)),
    Column('v_LocalOperationDivisionCode', String(6)),
    Column('v_OperationDivisionName', String(255)),
    Column('v_LocalOperationDivisionName', String(128)),
    Column('v_LocalDivisionCode', String(6)),
    Column('v_DivisionName', String(255)),
    Column('v_LocalDivisionName', String(128)),
    Column('v_LocalDepartmentCode', String(6)),
    Column('v_DepartmentName', String(255)),
    Column('v_LocalDepartmentName', String(128)),
    Column('v_LocalSectionCode', String(6)),
    Column('v_SectionName', String(255)),
    Column('v_LocalSectionName', String(128)),
    Column('v_TeamCode', String(4)),
    Column('v_GlobalFunctionCode', String(12)),
    Column('v_LocalTitleCode', String(2)),
    Column('v_Title', String(80)),
    Column('v_LocalTitle', String(80)),
    Column('v_OfficeCode', String(4)),
    Column('v_OfficeName', String(100)),
    Column('v_LocalOfficeName', String(100)),
    Column('v_OfficePostalCode', String(20)),
    Column('v_OfficePostalAddress', String(120)),
    Column('v_LocalOfficePostalAddress', String(120)),
    Column('v_OfficeTelephoneNumber', String(20)),
    Column('v_GlobalBusinessCode', String(2)),
    Column('v_CreateDate', DateTime),
    Column('v_UpdateDate', DateTime),
    Column('v_DirectoryReflectStartDate', DateTime),
    Column('v_DirectoryReflectEndDate', DateTime)
)
